openapi: 3.0.0
info:
  title: EPAS Token API
  description: This API provides a company token for accessing EPAS system.
  version: 1.0.0
servers:
  - url: not ready
paths:
  /instance_token:
    get:
      summary: Get instance Token for AO saas
      parameters:
        - name: x-user-id
          in: header
          required: true
          schema:
            type: string
          description: The ID of the user
        - name: x-account-id
          in: header
          required: true
          schema:
            type: string
          description: The ID of the user's account
        - name: x-user-role
          in: header
          required: true
          schema:
            type: string
          description: The role of the user
        - name: x-role-id
          in: header
          required: true
          schema:
            type: string
          description: The ID of the user's role
      description: |
        This API returns a instance token that can be used to access the ao saas instance.
      responses:
        '200':
          description: SUCCESS
          content:
            application/json: # operation response mime type
              schema: # response schema can be specified for each response
                $ref: '#/components/schemas/InstanceToken'
        
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Unauthorized'
              example:
                detail: Incorrect authentication credentials.
        "404":
          description: Token not found
          content:
            application/json:
              schema:
                $ref: '#/components/responses/TokenNotFound'
              example:
                detail: token not found.
      security:
        - bearerAuth: []
      tags:
        - EPAS


components:
  
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    InstanceToken:
      type: object
      required:
        - token
        - expired_time
      properties:
        token:
          type: string
          description: Token string for authentication
        expired_time:
          type: integer
          format: int64
          description: Unix timestamp of the token expiration time
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    TokenNotFound:
      description: Token not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

